services:
  db:
    image: postgres:16.3    
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    container_name: waiter-assistant
    volumes:
      - ./postgres:/var/lib/postgresql/data
